<?php
/** @var $block \Magento\Framework\View\Element\Html\Links
 * @var $escaper \Magento\Framework\Escaper
 * */
?>
<div class="block account-nav">
    <div class="title">
        <strong><?= $escaper->escapeHtml(__('Customer')) ?></strong>
    </div>
    <div class="content">
        <nav class="account-nav">
            <ul class="nav items">
                <?= $block->getChildHtml() ?>
            </ul>
        </nav>
    </div>
</div>
