<?php
/**
 * @var \Magento\Theme\Block\Html\Header $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<div class="top-header">
    <nav class="top-navigation">
        <ul>
            <li><a href="#"></a><?=$escaper->escapeHtml(__('Delivery and Payment'))?></li>
            <li><a href="#"></a><?=$escaper->escapeHtml(__('Wholesale customers'))?></li>
            <li><a href="#"></a><?=$escaper->escapeHtml(__('Contacts'))?></li>
        </ul>
    </nav>
    <div class="currency-language">
        <div class="currency">
            <span class="currency__text"><?= $escaper->escapeHtml(__('Exchange rate'))?></span>
            <span class="currency__dollar">$ 27.95</span>
            <span class="currency__euro">&euro; 33.50</span>
        </div>
        <div class="language-switcher">
            <a href="#">RU</a> |
            <a href="#">UA</a>
        </div>
    </div>
</div>
